language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r requirments.txt
env:
  -
# command to run tests
script:
  - nosetests --with-coverage
after_success:
  - coveralls
