kind: Service
apiVersion: v1
metadata:
  #Service name
  name: flask-app-svc2
spec:
  selector:
    app: medsender-playground
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
